<?php
// Local diagnostic page. Open only through Apache: /helping-hands/database_check.php
$host='localhost';$db='helpinghands_db';$user='root';$pass='';$ok=false;$message='';$tables=[];
try{
  $pdo=new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
  $ok=true;$message='Connection successful. The Helping Hands database is reachable.';
  foreach(['users','requests','volunteers','contact_messages','newsletter_subscribers'] as $t){$q=$pdo->query("SELECT COUNT(*) FROM `$t`");$tables[$t]=(int)$q->fetchColumn();}
}catch(Throwable $e){$message=$e->getMessage();}
function h($v){return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Database Check | Helping Hands</title><link rel="stylesheet" href="common.css"></head><body><main class="setup-error"><div class="panel"><div class="brand-mark">HH</div><span class="eyebrow">SYSTEM CHECK</span><h1>Helping Hands database check</h1><div class="alert <?php echo $ok?'success':'error'; ?>"><?php echo h($message); ?></div><?php if($ok): ?><p><strong>Database:</strong> <?php echo h($db); ?></p><div class="table-wrap"><table class="data-table"><thead><tr><th>Table</th><th>Records</th></tr></thead><tbody><?php foreach($tables as $name=>$count): ?><tr><td><?php echo h($name); ?></td><td><?php echo $count; ?></td></tr><?php endforeach; ?></tbody></table></div><div style="margin-top:20px;display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><a class="btn secondary" href="view-data.php">View My Data</a><a class="btn primary" href="index.php">Open website</a></div><div style="margin-top:12px;text-align:center"><a href="http://localhost/phpmyadmin/" target="_blank" rel="noopener" style="font-size:11px;color:var(--teal-dark);font-weight:700">Open the same database in phpMyAdmin →</a></div><?php else: ?><p>Start MySQL in XAMPP, run <strong>setup_local.php</strong>, then return here.</p><a class="btn secondary" href="setup_local.php">Open setup</a><?php endif; ?><p class="muted" style="margin-top:22px">For security, remove or rename this diagnostic page before production deployment.</p></div></main></body></html>
